spring:
  jpa:
    hibernate:
      ddl-auto: none #create, create-drop, update ...
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    jdbc:
      store-type: jdbc
      table-name: SPRING_SESSION
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:ALL_inserts_lockless.sql

kakao:
  client-id: 8c726ec0ff9d015553a536f3bfa6f551
  redirect-uri: http://localhost:3000/redirect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: false # Secure 비활성화
        same-site: none # Lax로 설정