spring:
  jpa:
    hibernate:
      ddl-auto: create #create, create-drop, update ...
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-other: true # 브라우저에서 접근 가능하도록 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
#   sql:
#     init:
#       mode: always
# #      schema-locations: classpath:
# #        data-locations: classpath:

kakao:
  client-id: 8c726ec0ff9d015553a536f3bfa6f551
  redirect-uri: http://localhost:3000/redirect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
server:
  servlet:
    session:
      cookie:
        secure: false # Secure 비활성화
        same-site: none # Lax로 설정