spring:
  jpa:
    hibernate:
      ddl-auto: create #create, create-drop, update ...
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-other: true # 브라우저에서 접근 가능하도록 설정

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL;
    username: sa
    password:
#   sql:
#     init:
#       mode: always
# #      schema-locations: classpath:
# #        data-locations: classpath:
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace